In [75]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [76]:
URL = ""
data = pd.read_csv(r"/Users/apple/Documents/programming/datas/Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [77]:
x = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [78]:
from sklearn.preprocessing import LabelEncoder
data = LabelEncoder()
x[:, 2] = data.fit_transform(x[:, 2])


In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
column = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(column.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [84]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
235/235 [==============================] - 2s 3ms/step - loss: 0.6895 - accuracy: 0.6171
Epoch 2/100
235/235 [==============================] - 1s 4ms/step - loss: 0.5089 - accuracy: 0.7928
Epoch 3/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4795 - accuracy: 0.7965
Epoch 4/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4627 - accuracy: 0.7964
Epoch 5/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4503 - accuracy: 0.7977
Epoch 6/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4408 - accuracy: 0.8016
Epoch 7/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4330 - accuracy: 0.8084
Epoch 8/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4270 - accuracy: 0.8121
Epoch 9/100
235/235 [==============================] - 1s 2ms/step - loss: 0.4223 - accuracy: 0.8159
Epoch 10/100
235/235 [==============================] - 1s 4ms/step - loss: 0.4178 - accura

Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7fb093466dc0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 545, in __del__
    gen_dataset_ops.delete_iterator(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1263, in delete_iterator
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt: 


In [87]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [85]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1928   61]
 [ 306  205]]


0.8532